version: 2

ci_steps: &ci_steps
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - run:
        name: Running tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

          bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

    - store_test_results:
        path: /tmp/test-results

    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

jobs:
  run_ci_ruby264:
    docker:
      - image: cimg/ruby:2.6.4
    <<: *ci_steps
  run_ci_ruby256:
    docker:
      - image: cimg/ruby:2.5.6
    <<: *ci_steps
  run_ci_ruby248:
    docker:
      - image: cimg/ruby:2.4.8
    <<: *ci_steps

workflows:
  version: 2
  run_ci:
    jobs:
      - run_ci_ruby264
      - run_ci_ruby256
      - run_ci_ruby248
